# Generated by Django 2.2 on 2019-09-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail автора')),
                ('record', models.TextField(max_length=2000, verbose_name='Текст записи')),
                ('create_date', models.DateTimeField(editable=False, verbose_name='Время создания')),
                ('edited_date', models.DateTimeField(verbose_name='Время редактирования')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default=('active', 'Активно'), max_length=15, verbose_name='Статус')),
            ],
        ),
    ]
