# Generated by Django 2.2 on 2019-09-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='records',
            name='edited_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время редактирования'),
        ),
    ]
