# Generated by Django 2.2 on 2019-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190921_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=15, verbose_name='Статус'),
        ),
    ]
